// 媒体头像
const meititouxiang = [
  {
    src: require('@/assets/img/touxiang/央视新闻.png'),
    huabuObj: {
      backgroundColor: 'rgba(13, 40, 188, 1)',
      backgroundImage: '',
      borderColor: '#000',
      borderRadius: 0,
      borderSize: 0,
      h: 400,
      name: '画布',
      shadow1: 0,
      shadow2: 0,
      shadow3: 0,
      shadowColor: '#000',
      shadowDirection: '',
      type: '画布',
      w: 400
    },
    elemList: [
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611472,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '视',
        textDecoration: '',
        type: '输入文字',
        w: 83,
        x: 235,
        y: 97,
        zIndex: 3
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(214, 232, 7, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611000,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '新',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 87,
        y: 249,
        zIndex: 2
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215610536,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '闻',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 238,
        y: 251,
        zIndex: 1
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215563705,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '央',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 83,
        y: 99,
        zIndex: 0
      }
    ]
  },
  {
    src: require('@/assets/img/touxiang/央视新闻.png'),
    huabuObj: {
      backgroundColor: 'rgba(13, 40, 188, 1)',
      backgroundImage: '',
      borderColor: '#000',
      borderRadius: 0,
      borderSize: 0,
      h: 400,
      name: '画布',
      shadow1: 0,
      shadow2: 0,
      shadow3: 0,
      shadowColor: '#000',
      shadowDirection: '',
      type: '画布',
      w: 400
    },
    elemList: [
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611472,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '视',
        textDecoration: '',
        type: '输入文字',
        w: 83,
        x: 235,
        y: 97,
        zIndex: 3
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(214, 232, 7, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611000,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '新',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 87,
        y: 249,
        zIndex: 2
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215610536,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '闻',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 238,
        y: 251,
        zIndex: 1
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215563705,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '央',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 83,
        y: 99,
        zIndex: 0
      }
    ]
  },
  {
    src: require('@/assets/img/touxiang/央视新闻.png'),
    huabuObj: {
      backgroundColor: 'rgba(13, 40, 188, 1)',
      backgroundImage: '',
      borderColor: '#000',
      borderRadius: 0,
      borderSize: 0,
      h: 400,
      name: '画布',
      shadow1: 0,
      shadow2: 0,
      shadow3: 0,
      shadowColor: '#000',
      shadowDirection: '',
      type: '画布',
      w: 400
    },
    elemList: [
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611472,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '视',
        textDecoration: '',
        type: '输入文字',
        w: 83,
        x: 235,
        y: 97,
        zIndex: 3
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(214, 232, 7, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611000,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '新',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 87,
        y: 249,
        zIndex: 2
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215610536,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '闻',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 238,
        y: 251,
        zIndex: 1
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215563705,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '央',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 83,
        y: 99,
        zIndex: 0
      }
    ]
  },
  {
    src: require('@/assets/img/touxiang/央视新闻.png'),
    huabuObj: {
      backgroundColor: 'rgba(13, 40, 188, 1)',
      backgroundImage: '',
      borderColor: '#000',
      borderRadius: 0,
      borderSize: 0,
      h: 400,
      name: '画布',
      shadow1: 0,
      shadow2: 0,
      shadow3: 0,
      shadowColor: '#000',
      shadowDirection: '',
      type: '画布',
      w: 400
    },
    elemList: [
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611472,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '视',
        textDecoration: '',
        type: '输入文字',
        w: 83,
        x: 235,
        y: 97,
        zIndex: 3
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(214, 232, 7, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611000,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '新',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 87,
        y: 249,
        zIndex: 2
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215610536,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '闻',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 238,
        y: 251,
        zIndex: 1
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215563705,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '央',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 83,
        y: 99,
        zIndex: 0
      }
    ]
  },
  {
    src: require('@/assets/img/touxiang/央视新闻.png'),
    huabuObj: {
      backgroundColor: 'rgba(13, 40, 188, 1)',
      backgroundImage: '',
      borderColor: '#000',
      borderRadius: 0,
      borderSize: 0,
      h: 400,
      name: '画布',
      shadow1: 0,
      shadow2: 0,
      shadow3: 0,
      shadowColor: '#000',
      shadowDirection: '',
      type: '画布',
      w: 400
    },
    elemList: [
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611472,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '视',
        textDecoration: '',
        type: '输入文字',
        w: 83,
        x: 235,
        y: 97,
        zIndex: 3
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(214, 232, 7, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611000,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '新',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 87,
        y: 249,
        zIndex: 2
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215610536,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '闻',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 238,
        y: 251,
        zIndex: 1
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215563705,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '央',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 83,
        y: 99,
        zIndex: 0
      }
    ]
  },
  {
    src: require('@/assets/img/touxiang/央视新闻.png'),
    huabuObj: {
      backgroundColor: 'rgba(13, 40, 188, 1)',
      backgroundImage: '',
      borderColor: '#000',
      borderRadius: 0,
      borderSize: 0,
      h: 400,
      name: '画布',
      shadow1: 0,
      shadow2: 0,
      shadow3: 0,
      shadowColor: '#000',
      shadowDirection: '',
      type: '画布',
      w: 400
    },
    elemList: [
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611472,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '视',
        textDecoration: '',
        type: '输入文字',
        w: 83,
        x: 235,
        y: 97,
        zIndex: 3
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(214, 232, 7, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611000,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '新',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 87,
        y: 249,
        zIndex: 2
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215610536,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '闻',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 238,
        y: 251,
        zIndex: 1
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215563705,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '央',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 83,
        y: 99,
        zIndex: 0
      }
    ]
  },
  {
    src: require('@/assets/img/touxiang/央视新闻.png'),
    huabuObj: {
      backgroundColor: 'rgba(13, 40, 188, 1)',
      backgroundImage: '',
      borderColor: '#000',
      borderRadius: 0,
      borderSize: 0,
      h: 400,
      name: '画布',
      shadow1: 0,
      shadow2: 0,
      shadow3: 0,
      shadowColor: '#000',
      shadowDirection: '',
      type: '画布',
      w: 400
    },
    elemList: [
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611472,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '视',
        textDecoration: '',
        type: '输入文字',
        w: 83,
        x: 235,
        y: 97,
        zIndex: 3
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(214, 232, 7, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611000,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '新',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 87,
        y: 249,
        zIndex: 2
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215610536,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '闻',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 238,
        y: 251,
        zIndex: 1
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215563705,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '央',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 83,
        y: 99,
        zIndex: 0
      }
    ]
  },
  {
    src: require('@/assets/img/touxiang/央视新闻.png'),
    huabuObj: {
      backgroundColor: 'rgba(13, 40, 188, 1)',
      backgroundImage: '',
      borderColor: '#000',
      borderRadius: 0,
      borderSize: 0,
      h: 400,
      name: '画布',
      shadow1: 0,
      shadow2: 0,
      shadow3: 0,
      shadowColor: '#000',
      shadowDirection: '',
      type: '画布',
      w: 400
    },
    elemList: [
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611472,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '视',
        textDecoration: '',
        type: '输入文字',
        w: 83,
        x: 235,
        y: 97,
        zIndex: 3
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(214, 232, 7, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611000,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '新',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 87,
        y: 249,
        zIndex: 2
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215610536,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '闻',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 238,
        y: 251,
        zIndex: 1
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215563705,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '央',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 83,
        y: 99,
        zIndex: 0
      }
    ]
  },
  {
    src: require('@/assets/img/touxiang/央视新闻.png'),
    huabuObj: {
      backgroundColor: 'rgba(13, 40, 188, 1)',
      backgroundImage: '',
      borderColor: '#000',
      borderRadius: 0,
      borderSize: 0,
      h: 400,
      name: '画布',
      shadow1: 0,
      shadow2: 0,
      shadow3: 0,
      shadowColor: '#000',
      shadowDirection: '',
      type: '画布',
      w: 400
    },
    elemList: [
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611472,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '视',
        textDecoration: '',
        type: '输入文字',
        w: 83,
        x: 235,
        y: 97,
        zIndex: 3
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(214, 232, 7, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611000,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '新',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 87,
        y: 249,
        zIndex: 2
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215610536,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '闻',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 238,
        y: 251,
        zIndex: 1
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215563705,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '央',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 83,
        y: 99,
        zIndex: 0
      }
    ]
  },
  {
    src: require('@/assets/img/touxiang/央视新闻.png'),
    huabuObj: {
      backgroundColor: 'rgba(13, 40, 188, 1)',
      backgroundImage: '',
      borderColor: '#000',
      borderRadius: 0,
      borderSize: 0,
      h: 400,
      name: '画布',
      shadow1: 0,
      shadow2: 0,
      shadow3: 0,
      shadowColor: '#000',
      shadowDirection: '',
      type: '画布',
      w: 400
    },
    elemList: [
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611472,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '视',
        textDecoration: '',
        type: '输入文字',
        w: 83,
        x: 235,
        y: 97,
        zIndex: 3
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(214, 232, 7, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611000,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '新',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 87,
        y: 249,
        zIndex: 2
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215610536,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '闻',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 238,
        y: 251,
        zIndex: 1
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215563705,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '央',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 83,
        y: 99,
        zIndex: 0
      }
    ]
  },
  {
    src: require('@/assets/img/touxiang/央视新闻.png'),
    huabuObj: {
      backgroundColor: 'rgba(13, 40, 188, 1)',
      backgroundImage: '',
      borderColor: '#000',
      borderRadius: 0,
      borderSize: 0,
      h: 400,
      name: '画布',
      shadow1: 0,
      shadow2: 0,
      shadow3: 0,
      shadowColor: '#000',
      shadowDirection: '',
      type: '画布',
      w: 400
    },
    elemList: [
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611472,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '视',
        textDecoration: '',
        type: '输入文字',
        w: 83,
        x: 235,
        y: 97,
        zIndex: 3
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(214, 232, 7, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611000,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '新',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 87,
        y: 249,
        zIndex: 2
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215610536,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '闻',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 238,
        y: 251,
        zIndex: 1
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215563705,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '央',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 83,
        y: 99,
        zIndex: 0
      }
    ]
  },
  {
    src: require('@/assets/img/touxiang/央视新闻.png'),
    huabuObj: {
      backgroundColor: 'rgba(13, 40, 188, 1)',
      backgroundImage: '',
      borderColor: '#000',
      borderRadius: 0,
      borderSize: 0,
      h: 400,
      name: '画布',
      shadow1: 0,
      shadow2: 0,
      shadow3: 0,
      shadowColor: '#000',
      shadowDirection: '',
      type: '画布',
      w: 400
    },
    elemList: [
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611472,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '视',
        textDecoration: '',
        type: '输入文字',
        w: 83,
        x: 235,
        y: 97,
        zIndex: 3
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(214, 232, 7, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215611000,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '新',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 87,
        y: 249,
        zIndex: 2
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215610536,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '闻',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 238,
        y: 251,
        zIndex: 1
      },
      {
        backgroundColor: '',
        backgroundImage: '',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 140,
        fontStyle: '',
        fontWeight: 'normal',
        h: 40,
        id: 1622215563705,
        isActive: false,
        name: '输入文字',
        parentLimitation: false,
        rotate: 0,
        shadow1: 0,
        shadow2: 0,
        shadow3: 0,
        shadowColor: '#000',
        text: '央',
        textDecoration: '',
        type: '输入文字',
        w: 80,
        x: 83,
        y: 99,
        zIndex: 0
      }
    ]
  }
]
export { meititouxiang }
